const DEFAULT_SETTINGS = { language: 'en-US', voiceURI: '', rate: 1, volume: 1, uiLanguage: 'en', highContrast: false };
const messages = {
  en: {
    tagline:'Read with focus', ready:'Ready', reading:'Reading', paused:'Paused', stopped:'Stopped', completed:'Completed', error:'Needs attention', noText:'No sentence yet.', noSelection:'Select some visible text first, then open SmartRead and try again.', noReadableText:'SmartRead could not find readable text on this page.', noVoice:'No voice is available. Check Chrome and system audio settings.', pageRestricted:'Chrome does not allow extensions to read this page. Open a regular website.', tabUnavailable:'That page is no longer available.', connectionError:'SmartRead could not connect to this page. Reload the page and try again.', readSelection:'Read selected text', readPage:'Read this page', current:'Current sentence', progress:'Reading progress', noProgress:'No active text', settings:'Reading controls', settingsHint:'Adjust the sound without leaving this panel.', rate:'Speed', volume:'Volume', slower:'Slower', faster:'Faster', quieter:'Quieter', louder:'Louder', advanced:'Language and voice', advancedClose:'Language and voice', interface:'Interface', speechLanguage:'Reading language', voice:'Voice', automaticVoice:'Automatic (recommended)', noVoices:'No compatible installed voices', previous:'Previous sentence', play:'Play or resume', pause:'Pause', stop:'Stop', next:'Next sentence', saved:'Setting saved and applied', savedLater:'Saved. It will apply when reading starts.', resetDone:'Settings restored', contrast:'High contrast', contrastHint:'Stronger colors and focus indicators', reset:'Reset settings', docs:'Documentation ↗', keyboard:'Keyboard: Space play/pause · ← previous · → next', tutorialTitle:'Your first reading', tutorial1:'Select text on the page, or choose the full page.', tutorial2:'Press Play and adjust the speed.', tutorial3:'SmartRead highlights the current sentence.', tutorialDone:'Got it'
  }
};

const id = (value) => document.getElementById(value);
const refs = {
  popup:document.querySelector('.smartread-popup'), tagline:id('tagline'), status:id('smartreadStatus'), statusText:id('statusText'), onboarding:id('onboarding'), onboardingTitle:id('onboardingTitle'), onboardingStep1:id('onboardingStep1'), onboardingStep2:id('onboardingStep2'), onboardingStep3:id('onboardingStep3'), dismissOnboarding:id('dismissOnboarding'), readSelection:id('readSelection'), readPage:id('readPage'), previous:id('previous'), play:id('play'), pause:id('pause'), stop:id('stop'), next:id('next'), currentSentence:id('currentSentence'), readProgress:id('readProgress'), progressFill:id('progressFill'), progressText:id('progressText'), labelCurrent:id('labelCurrentSentence'), settingsTitle:id('settingsTitle'), settingsHint:id('settingsHint'), rateRange:id('rateRange'), rateLabel:id('rateLabel'), rateDown:id('rateDown'), rateUp:id('rateUp'), labelRate:id('labelRate'), volumeRange:id('volumeRange'), volumeLabel:id('volumeLabel'), volumeDown:id('volumeDown'), volumeUp:id('volumeUp'), labelVolume:id('labelVolume'), feedback:id('settingFeedback'), highContrast:id('highContrast'), highContrastLabel:id('highContrastLabel'), highContrastHint:id('highContrastHint'), openOptions:id('openOptions'), advancedButtonText:id('advancedButtonText'), advancedSettings:id('advancedSettings'), uiLanguage:id('uiLanguage'), languageSelect:id('languageSelect'), voiceSelect:id('voiceSelect'), labelVoice:id('labelVoice'), labelSpeech:id('labelSpeechLanguage'), labelInterface:id('labelInterfaceLanguage'), resetSettings:id('resetSettings'), openDocumentation:id('openDocumentation'), keyboardHint:id('keyboardHint')
};

let uiLanguage = 'en';
let activeTabId = null;
let lastState = null;
let feedbackTimer = null;
const tr = (key) => messages.en[key] || key;

function describe(button, key) { const label = tr(key); button.title = label; button.setAttribute('aria-label', label); }
function applyLabels() {
  document.documentElement.lang = uiLanguage; refs.tagline.textContent = tr('tagline'); refs.readSelection.textContent = tr('readSelection'); refs.readPage.textContent = tr('readPage'); refs.labelCurrent.textContent = tr('current'); refs.settingsTitle.textContent = tr('settings'); refs.settingsHint.textContent = tr('settingsHint'); refs.labelRate.textContent = tr('rate'); refs.labelVolume.textContent = tr('volume'); refs.labelVoice.textContent = tr('voice'); refs.labelSpeech.textContent = tr('speechLanguage'); refs.labelInterface.textContent = tr('interface'); refs.highContrastLabel.textContent = tr('contrast'); refs.highContrastHint.textContent = tr('contrastHint'); refs.resetSettings.textContent = tr('reset'); refs.openDocumentation.textContent = tr('docs'); refs.keyboardHint.textContent = tr('keyboard'); refs.advancedButtonText.textContent = refs.advancedSettings.hidden ? tr('advanced') : tr('advancedClose'); refs.onboardingTitle.textContent = tr('tutorialTitle'); refs.onboardingStep1.textContent = tr('tutorial1'); refs.onboardingStep2.textContent = tr('tutorial2'); refs.onboardingStep3.textContent = tr('tutorial3'); refs.dismissOnboarding.textContent = tr('tutorialDone');
  describe(refs.previous,'previous'); describe(refs.play,'play'); describe(refs.pause,'pause'); describe(refs.stop,'stop'); describe(refs.next,'next'); describe(refs.rateDown,'slower'); describe(refs.rateUp,'faster'); describe(refs.volumeDown,'quieter'); describe(refs.volumeUp,'louder'); refs.readProgress.setAttribute('aria-label',tr('progress'));
}

async function findActiveTab() { const tabs = await chrome.tabs.query({active:true,currentWindow:true}); activeTabId = tabs[0]?.id || null; return activeTabId; }
async function send(payload) { try { const tabId = activeTabId || await findActiveTab(); if (!tabId) return {ok:false,errorCode:'NO_ACTIVE_TAB'}; return await chrome.runtime.sendMessage({...payload,tabId}); } catch (error) { return {ok:false,errorCode:'CONNECTION_ERROR',error:String(error?.message||error)}; } }
function friendlyError(code) { if (code==='NO_SELECTION') return tr('noSelection'); if (code==='NO_READABLE_TEXT') return tr('noReadableText'); if (code==='VOICE_ERROR') return tr('noVoice'); if (code==='PAGE_RESTRICTED') return tr('pageRestricted'); if (code==='TAB_UNAVAILABLE'||code==='NO_ACTIVE_TAB') return tr('tabUnavailable'); return tr('connectionError'); }
function showFeedback(message,isError=false) { clearTimeout(feedbackTimer); refs.feedback.textContent=message; refs.feedback.classList.toggle('is-error',isError); feedbackTimer=setTimeout(()=>{refs.feedback.textContent='';refs.feedback.classList.remove('is-error');},2600); }

async function applySettings(settings) {
  const stored = await chrome.runtime.sendMessage({type:'smartread_save_settings',settings});
  if (stored?.ok===false) { showFeedback(friendlyError(stored.errorCode),true); return false; }
  const applied = await send({type:'smartread_command',action:'SMARTREAD_SET_SETTINGS',settings});
  showFeedback(applied?.ok ? tr('saved') : tr('savedLater')); return true;
}

function updateRange(input,output,formatter) { const value=Number(input.value); const progress=((value-Number(input.min))/(Number(input.max)-Number(input.min)))*100; input.style.setProperty('--range-progress',`${Math.max(0,Math.min(progress,100))}%`); output.textContent=formatter(value); }
function updateRanges() { updateRange(refs.rateRange,refs.rateLabel,(value)=>`${value.toFixed(2)}x`); updateRange(refs.volumeRange,refs.volumeLabel,(value)=>`${Math.round(value*100)}%`); }
function setContrast(enabled) { refs.highContrast.checked=enabled; refs.popup.classList.toggle('high-contrast',enabled); }
function statusLabel(status) { return tr(['ready','reading','paused','stopped','completed','error'].includes(status)?status:'ready'); }
function updateProgress(state) { const valid=state?.hasText&&Number.isFinite(state.total)&&state.total>0&&Number.isFinite(state.currentIndex); const current=valid?Math.min(Math.max(state.currentIndex+1,1),state.total):0; const total=valid?state.total:0; refs.readProgress.setAttribute('aria-valuemax',String(total)); refs.readProgress.setAttribute('aria-valuenow',String(current)); refs.progressFill.style.width=`${total?(current/total)*100:0}%`; refs.progressText.textContent=valid?`${current} / ${total}`:tr('noProgress'); }
function renderState(state) { lastState=state; const status=state?.status||(state?.errorCode?'error':'ready'); refs.statusText.textContent=statusLabel(status); refs.status.setAttribute('aria-label',statusLabel(status)); refs.status.title=statusLabel(status); refs.popup.classList.toggle('is-reading',status==='reading'); refs.popup.classList.toggle('is-paused',status==='paused'); refs.popup.classList.toggle('is-completed',status==='completed'); refs.popup.classList.toggle('has-error',status==='error'); updateProgress(state); refs.currentSentence.textContent=state?.errorCode?friendlyError(state.errorCode):state?.hasText&&state.currentIndex>=0?(state.currentSentence||tr('noText')):tr('noText'); refs.play.disabled=status==='reading'; refs.pause.disabled=status!=='reading'; refs.stop.disabled=!['reading','paused'].includes(status); refs.previous.disabled=!state?.canPrevious; refs.next.disabled=!state?.canNext; }

async function refreshVoices(selected='', language=refs.languageSelect.value) {
  const response=await send({type:'smartread_command',action:'SMARTREAD_GET_VOICES'});
  refs.voiceSelect.replaceChildren();
  const automatic=document.createElement('option');
  automatic.value='';
  automatic.textContent=tr('automaticVoice');
  refs.voiceSelect.appendChild(automatic);
  const languageBase=String(language||DEFAULT_SETTINGS.language).toLowerCase().split(/[-_]/)[0];
  const exactLanguage=String(language||DEFAULT_SETTINGS.language).toLowerCase().replace('_','-');
  const compatible=(response?.ok&&Array.isArray(response.voices)?response.voices:[])
    .filter((voice)=>String(voice.lang||'').toLowerCase().split(/[-_]/)[0]===languageBase)
    .sort((first,second)=>{
      const firstExact=String(first.lang||'').toLowerCase().replace('_','-')===exactLanguage?0:1;
      const secondExact=String(second.lang||'').toLowerCase().replace('_','-')===exactLanguage?0:1;
      if(firstExact!==secondExact)return firstExact-secondExact;
      if(first.default!==second.default)return first.default?-1:1;
      return first.name.localeCompare(second.name);
    });
  for(const voice of compatible){const option=document.createElement('option');option.value=voice.voiceURI;option.textContent=`${voice.name} (${voice.lang})${voice.default?' · default':''}`;refs.voiceSelect.appendChild(option);}
  if(!compatible.length){const option=document.createElement('option');option.value='unavailable';option.textContent=tr('noVoices');option.disabled=true;refs.voiceSelect.appendChild(option);}
  refs.voiceSelect.disabled=false;
  refs.voiceSelect.value=compatible.some((voice)=>voice.voiceURI===selected)?selected:'';
}
async function refreshState() { const state=await send({type:'smartread_command',action:'SMARTREAD_GET_STATE'}); if(!state?.ok){renderState({status:'error',errorCode:state?.errorCode||'CONNECTION_ERROR'});return;} const settings=state.settings||{}; if(settings.uiLanguage&&settings.uiLanguage!==uiLanguage){uiLanguage=settings.uiLanguage;refs.uiLanguage.value=uiLanguage;applyLabels();} if(settings.language&&refs.languageSelect.value!==settings.language){refs.languageSelect.value=settings.language;await refreshVoices(settings.voiceURI||'',settings.language);}else if(settings.voiceURI&&refs.voiceSelect.options.length){refs.voiceSelect.value=settings.voiceURI;}if(settings.rate!=null&&document.activeElement!==refs.rateRange)refs.rateRange.value=String(settings.rate);if(settings.volume!=null&&document.activeElement!==refs.volumeRange)refs.volumeRange.value=String(settings.volume);if(settings.highContrast!=null)setContrast(settings.highContrast);updateRanges();renderState(state); }
async function command(action) { const response=await send({type:'smartread_command',action}); if(!response?.ok){renderState({status:'error',errorCode:response?.errorCode||'CONNECTION_ERROR'});return;} if(response.state)renderState(response.state);else await refreshState(); }
function showAdvanced(show){refs.advancedSettings.hidden=!show;refs.openOptions.setAttribute('aria-expanded',String(show));refs.advancedButtonText.textContent=show?tr('advancedClose'):tr('advanced');}
async function step(input,amount,name){input.value=String(Math.max(Number(input.min),Math.min(Number(input.max),Number((Number(input.value)+amount).toFixed(2)))));updateRanges();await applySettings({[name]:Number(input.value)});}

refs.readSelection.addEventListener('click',()=>command('SMARTREAD_START_SELECTION'));refs.readPage.addEventListener('click',()=>command('SMARTREAD_START_PAGE'));refs.play.addEventListener('click',()=>command('SMARTREAD_PLAY'));refs.pause.addEventListener('click',()=>command('SMARTREAD_PAUSE'));refs.stop.addEventListener('click',()=>command('SMARTREAD_STOP'));refs.previous.addEventListener('click',()=>command('SMARTREAD_PREVIOUS'));refs.next.addEventListener('click',()=>command('SMARTREAD_NEXT'));
refs.rateRange.addEventListener('input',updateRanges);refs.rateRange.addEventListener('change',()=>applySettings({rate:Number(refs.rateRange.value)}));refs.rateDown.addEventListener('click',()=>step(refs.rateRange,-.1,'rate'));refs.rateUp.addEventListener('click',()=>step(refs.rateRange,.1,'rate'));refs.volumeRange.addEventListener('input',updateRanges);refs.volumeRange.addEventListener('change',()=>applySettings({volume:Number(refs.volumeRange.value)}));refs.volumeDown.addEventListener('click',()=>step(refs.volumeRange,-.1,'volume'));refs.volumeUp.addEventListener('click',()=>step(refs.volumeRange,.1,'volume'));
refs.openOptions.addEventListener('click',()=>showAdvanced(true));refs.highContrast.addEventListener('change',async()=>{setContrast(refs.highContrast.checked);await applySettings({highContrast:refs.highContrast.checked});});refs.uiLanguage.addEventListener('change',async(event)=>{uiLanguage=event.target.value;applyLabels();if(lastState)renderState(lastState);await applySettings({uiLanguage});});refs.languageSelect.addEventListener('change',async(event)=>{const language=event.target.value;await applySettings({language,voiceURI:''});await refreshVoices('',language);});refs.voiceSelect.addEventListener('change',()=>applySettings({voiceURI:refs.voiceSelect.value||''}));
refs.dismissOnboarding.addEventListener('click',async()=>{refs.onboarding.hidden=true;await chrome.storage.local.set({smartReadOnboardingSeen:true});refs.readSelection.focus();});
refs.resetSettings.addEventListener('click',async()=>{uiLanguage=DEFAULT_SETTINGS.uiLanguage;refs.uiLanguage.value=uiLanguage;refs.languageSelect.value=DEFAULT_SETTINGS.language;refs.rateRange.value=String(DEFAULT_SETTINGS.rate);refs.volumeRange.value=String(DEFAULT_SETTINGS.volume);setContrast(false);applyLabels();updateRanges();await applySettings(DEFAULT_SETTINGS);showFeedback(tr('resetDone'));await refreshVoices();});
refs.openDocumentation.addEventListener('click',()=>chrome.tabs.create({url:chrome.runtime.getURL('docs/index.html')}));
document.addEventListener('keydown',(event)=>{if(event.target instanceof HTMLInputElement||event.target instanceof HTMLSelectElement||event.target instanceof HTMLButtonElement)return;if(event.key===' '){event.preventDefault();command(lastState?.status==='reading'?'SMARTREAD_PAUSE':'SMARTREAD_PLAY');}if(event.key==='ArrowLeft'){event.preventDefault();command('SMARTREAD_PREVIOUS');}if(event.key==='ArrowRight'){event.preventDefault();command('SMARTREAD_NEXT');}if(event.key==='Escape'&&!refs.onboarding.hidden)refs.dismissOnboarding.focus();});
chrome.runtime.onMessage.addListener((message)=>{if(message?.type==='smartread_state_update'&&message.tabId===activeTabId&&message.state)renderState(message.state);});chrome.tabs.onActivated.addListener(async({tabId})=>{activeTabId=tabId;await refreshState();});

async function initialize(){activeTabId=await findActiveTab();const stored=await chrome.storage.local.get(['smartReadSettings','smartReadOnboardingSeen']);const settings={...DEFAULT_SETTINGS,...(stored.smartReadSettings||{}),uiLanguage:'en'};uiLanguage='en';refs.uiLanguage.value='en';refs.languageSelect.value=settings.language;refs.rateRange.value=String(settings.rate);refs.volumeRange.value=String(settings.volume);setContrast(settings.highContrast);refs.onboarding.hidden=stored.smartReadOnboardingSeen===true;showAdvanced(true);applyLabels();updateRanges();await chrome.runtime.sendMessage({type:'smartread_save_settings',settings:{uiLanguage:'en'}});await refreshVoices(settings.voiceURI,settings.language);await refreshState();if(!refs.onboarding.hidden)refs.dismissOnboarding.focus();}
initialize().catch(()=>renderState({status:'error',errorCode:'CONNECTION_ERROR'}));
